version: "3"
services:
  springboot-app:
    # container_name: spring-app
    image: app
    restart: always
    build: .
    ports:
      - 8090:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: danielsan6697
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
#    volumes:
#      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: danielsan6697
